# Generated by Django 6.0.2 on 2026-02-11 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='ready', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='companies_c_status_2407e4_idx'), models.Index(fields=['name'], name='companies_c_name_2d8260_idx'), models.Index(fields=['contact_email'], name='companies_c_contact_2f513a_idx'), models.Index(fields=['created_at'], name='companies_c_created_301a54_idx')],
            },
        ),
    ]
